server:
  port: 8080

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka
  instance:
    hostname: localhost

#当前服务名称

spring:
  application:
    name: easy-write
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    jdbc-url: jdbc:mysql://192.168.52.100:3306/test?characterEncoding=utf-8
    slave1:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://192.168.52.110:3306/test?characterEncoding=utf-8
    slave2:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://192.168.52.120:3306/test?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

##################redis基础配置###################
spring.redis.host: 192.168.52.100
#Redis服务器连接端口
spring.redis.port: 6379
#Redis服务器连接密码（默认为空）
spring.redis.password:
#连接池最大连接数（使用负值表示没有限制）
spring.redis.pool.max-active: 8
#连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.pool.max-wait: -1
#连接池中的最大空闲连接
spring.redis.pool.max-idle: 8
#连接池中的最小空闲连接
spring.redis.pool.min-idle: 0
#连接超时时间（毫秒）
spring.redis.timeout: 30000



##mybatis config
## Mybatis-Plus Config http://mp.baomidou.com/#/spring-boot
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  typeAliasesPackage: com.york.easywrite.model
#  configuration:
#    map-underscore-to-camel-case: true

