server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: easy-read